"""
Tests for the save editor. Standard library only, so `py test_sas4.py` runs anywhere.

    py tests/test_sas4.py            run them
    py tests/test_sas4.py -v         and say what each one checked

Every save these tests touch is generated by `sas4_model.py` inside a temporary directory.
Nothing here reads a real profile, contains anyone's account data, or writes outside the
temp directory it made -- `BACKUPS` is redirected in setUp so a test run cannot leave
backups lying around beside the tools.

What is worth testing here is narrow and specific. The tools edit a file that cannot be
regenerated: FINDINGS.md records one hand edit that skipped a backup and made the game
discard the character, recoverable only by restoring a byte-identical copy. Three things
can destroy a save while still looking like they worked, and they are what these cover:

  * the checksum -- one wrong bit in the table and every file written is rejected by the
    game, which at least fails loudly;
  * `anchor_for` -- an anchor that resolves to the wrong place overwrites a different
    value and the checksum is still valid, so nothing complains until the game is opened;
  * the Claimed stream -- it is a flattened run-length format, so a parser that is off by
    one deletes the wrong item.

The rest of the suite guards the arithmetic that the level command depends on.
"""

import importlib.util
import json
import os
import shutil
import sys
import tempfile
import unittest

# The suite lives in tests/, the tools it imports sit one level up.
TOOLS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def read(path):
    """Bytes of a file, closed straight away -- a test suite should not warn about itself."""
    with open(path, "rb") as handle:
        return handle.read()


def _load(name):
    spec = importlib.util.spec_from_file_location(name, os.path.join(TOOLS, name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


dgdata = _load("dgdata")
sas4 = _load("sas4")
model = _load("sas4_model")


class Temp(unittest.TestCase):
    """A temporary directory, and backups redirected into it."""

    def setUp(self):
        self.dir = tempfile.mkdtemp(prefix="sas4-test-")
        self._backups = sas4.BACKUPS
        sas4.BACKUPS = os.path.join(self.dir, "backups")

    def tearDown(self):
        sas4.BACKUPS = self._backups
        shutil.rmtree(self.dir, ignore_errors=True)

    def make(self, level=5, money=1000, **kw):
        """A generated save on disk, and its path."""
        path = os.path.join(self.dir, "profile-%d.save" % len(os.listdir(self.dir)))
        document = model.generate(level=level, money=money, **kw)
        with open(path, "wb") as handle:
            handle.write(model.encode_document(document))
        return path


class TestFormat(Temp):
    """The container: the checksum, and the obfuscation around it."""

    def test_table_entry_is_not_crc32(self):
        # The whole finding in one number. A real CRC-32 table has 0x77073096 here; this
        # format's arithmetic int32 shift carries the sign bit down and produces 0x09073096.
        # If this ever reads 0x77073096 again, someone has "fixed" the shift.
        self.assertEqual(dgdata.TABLE[1], 0x09073096)

    def test_roundtrip_is_byte_identical(self):
        path = self.make()
        raw = read(path)
        self.assertEqual(dgdata.encode(dgdata.decode(raw)), raw)

    def test_decode_inverts_encode(self):
        plain = b'{"a":1,"b":"\xc3\xa9"}'
        self.assertEqual(dgdata.decode(dgdata.encode(plain)), plain)

    def test_verify_catches_a_flipped_byte(self):
        path = self.make()
        raw = bytearray(read(path))
        self.assertTrue(dgdata.verify(bytes(raw))[2])
        raw[dgdata.HEADER_LENGTH + 5] ^= 0x01          # one bit, in the body
        stored, computed, ok = dgdata.verify(bytes(raw))
        self.assertFalse(ok)
        self.assertNotEqual(stored, computed)

    def test_golden_vector_pins_the_constants(self):
        """A fixed plaintext and the exact bytes it must produce.

        Roundtrip tests cannot catch a changed BYTE_OFFSET or CYCLE: encode and decode
        share the constant, so they stay consistent with each other while producing a file
        the game would not read. Only a known-good pair of (plaintext, bytes) pins them,
        and this pair is invented here rather than taken from a real save -- the point is
        the format, and a real profile carries an account id.
        """
        plain = b'{"Version":{"link":"0"},"n":12345}'
        expected = bytes.fromhex(
            "444744415441306134343032326390386d7d8b8d7e85853a539537828086843c"
            "4f38473a9646378439524a4c484a4c95")
        self.assertEqual(dgdata.encode(plain), expected)
        self.assertEqual(dgdata.decode(expected), plain)
        self.assertEqual("%08x" % dgdata.checksum(plain), "0a44022c")
        self.assertEqual(dgdata.BYTE_OFFSET, 21)
        self.assertEqual(dgdata.CYCLE, 6)

    def test_decode_rejects_a_foreign_file(self):
        with self.assertRaises(ValueError):
            dgdata.decode(b"NOTDGDATA" + b"\x00" * 40)


class TestExperience(Temp):
    """The curve the level command depends on."""

    def test_formula_reproduces_every_observed_value(self):
        # The tabulated levels are the only real data; the closed form has to match them
        # exactly or the two disagree and one of them is wrong.
        for level, expected in enumerate(model.XP_TABLE):
            self.assertEqual(model.xp_for_level(level), expected,
                             "level %d" % level)

    def test_rounding_is_never_ambiguous(self):
        # floor and round can only differ on an exact .5, and 7*n^2*(n+1) mod 10 cannot be
        # 5 because n^2*(n+1) is always even. Asserted rather than argued.
        for n in range(1, model.MAX_LEVEL + 20):
            self.assertNotEqual((7 * n * n + 7 * n ** 3) % 10, 5, "level %d" % n)

    def test_curve_climbs_all_the_way_to_the_cap(self):
        for level in range(1, model.MAX_LEVEL + 1):
            self.assertLess(model.xp_for_level(level), model.xp_for_level(level + 1),
                            "level %d" % level)

    def test_every_level_lands_inside_its_own_band(self):
        # What `rule_xp_matches_level` enforces: the XP the level command writes has to be
        # in the band that level accepts, at every level, or a consistent edit is not.
        for level in range(1, model.MAX_LEVEL + 1):
            xp = model.xp_for_level(level)
            self.assertTrue(model.xp_for_level(level) <= xp < model.xp_for_level(level + 1),
                            "level %d" % level)


class TestByteEdit(Temp):
    """`set` changes the value it was asked for, and nothing else."""

    def test_only_the_named_value_changes(self):
        path = self.make(level=5, money=1000)
        before = dgdata.decode(read(path))
        _raw, document = sas4.load(path)
        ok, _saved, message = sas4.apply_edits(path, [("Inventory/Profile0/Money", 4242)])
        self.assertTrue(ok, message)
        after = dgdata.decode(read(path))

        # Everything outside the one run of differing bytes must be untouched. The runs
        # dgdata reports are the whole diff, so one run means one value moved.
        runs = dgdata.changed_fields(before, after)
        self.assertEqual(len(runs), 1, runs)
        self.assertIn("Money", runs[0][2])
        self.assertEqual(json.loads(after)["Inventory"]["Profile0"]["Money"], 4242)

    def test_length_change_shifts_nothing_before_it(self):
        # 1000 -> 4242 is the same width; 1000 -> 12345678 is not. The bytes ahead of the
        # value must still be identical, or the edit moved something it should not have.
        path = self.make(money=1000)
        before = dgdata.decode(read(path))
        sas4.apply_edits(path, [("Inventory/Profile0/Money", 12345678)])
        after = dgdata.decode(read(path))
        cut = before.index(b'"Money"')
        self.assertEqual(before[:cut], after[:cut])
        self.assertEqual(json.loads(after)["Inventory"]["Profile0"]["Money"], 12345678)

    def test_anchor_refuses_what_it_cannot_pin_down(self):
        path = self.make()
        _raw, document = sas4.load(path)
        plain = dgdata.decode(read(path))
        # A key that appears once resolves; a made-up path does not exist at all.
        anchor, length = sas4.anchor_for(document, plain, "Inventory/Profile0/Money")
        self.assertEqual(plain.count(anchor), 1)
        self.assertGreater(length, 0)
        with self.assertRaises((KeyError, TypeError, ValueError)):
            sas4.anchor_for(document, plain, "Inventory/Profile0/NoSuchField")

    def test_a_bad_path_leaves_the_file_untouched(self):
        path = self.make()
        original = read(path)
        ok, _saved, message = sas4.apply_edits(
            path, [("Inventory/Profile0/Money", 50), ("Inventory/Profile0/Nope", 1)])
        self.assertFalse(ok, message)
        self.assertEqual(read(path), original,
                         "a plan that cannot be applied must write nothing at all")


class TestLevel(Temp):
    """`level` moves four fields together, and gets the arithmetic right."""

    def test_writes_all_four_fields(self):
        path = self.make(level=3)
        _raw, document = sas4.load(path)
        plan, spent = sas4.level_plan(document, 40)
        self.assertEqual(spent, 0)
        self.assertEqual(dict(plan), {
            "Inventory/Profile0/Skills/PlayerLevel": 40,
            "Inventory/Profile0/Skills/PlayerTotalXp": model.xp_for_level(40),
            "Inventory/Profile0/Skills/AvailableSkillPoints": 40,
            "Global/HighestRank": 40,
        })

    def test_result_passes_every_consistency_rule(self):
        for level in (1, 2, 25, 26, 60, model.MAX_LEVEL):
            path = self.make(level=3)
            _raw, document = sas4.load(path)
            plan, _spent = sas4.level_plan(document, level)
            ok, _saved, message = sas4.apply_edits(path, plan)
            self.assertTrue(ok, message)
            self.assertEqual(model.check(sas4.load(path)[1]), [], "level %d" % level)

    def test_points_already_spent_come_off_the_grant(self):
        document = model.generate(level=3)
        document["Inventory"]["Profile0"]["Skills"]["SkillsArray"] = [
            {"SkillName": "holdtheline", "SkillLevel": 7}]
        document["Inventory"]["Profile0"]["Skills"]["AvailableSkillPoints"] = 0
        plan, spent = sas4.level_plan(document, 30)
        self.assertEqual(spent, 7)
        self.assertEqual(dict(plan)["Inventory/Profile0/Skills/AvailableSkillPoints"], 23)

    def test_highest_rank_is_never_lowered(self):
        document = model.generate(level=3)
        document["Global"]["HighestRank"] = 55
        plan, _spent = sas4.level_plan(document, 20)
        self.assertEqual(dict(plan)["Global/HighestRank"], 55)

    def test_out_of_range_is_refused(self):
        document = model.generate(level=3)
        for level in (0, -1, model.MAX_LEVEL + 1):
            with self.assertRaises(ValueError, msg="level %d" % level):
                sas4.level_plan(document, level)


class TestClaimed(Temp):
    """The run-length stream: grant, read back, and remove the right thing."""

    WEAPON, EQUIP = 129, 101

    def setUp(self):
        super().setUp()
        # These tests are about the stream's shape, not about item names, so stand a
        # minimal table in for the downloaded one rather than needing the network.
        self._cache = sas4._ITEM_CACHE
        sas4._ITEM_CACHE = {"weapon": {self.WEAPON: ("Test Gun", "smg")},
                            "equipment": {self.EQUIP: ("Test Vest", "vest")}}

    def tearDown(self):
        sas4._ITEM_CACHE = self._cache
        super().tearDown()

    def test_run_lengths(self):
        """Both kinds are four elements. Measured, not assumed -- see claimed_items.

        This asserted two for equipment until saves captured from the running game showed
        four, which is also what both published editors append. The wrong length made
        drop_claimed cut a run in half and leave its tail behind as loose integers.
        """
        document = model.generate()
        plan, labels = sas4.grant_plan(document, [(self.WEAPON, "weapon", 0, 0, 2)])
        self.assertEqual(len(plan[0][1]), 4, "a weapon is four elements")
        plan, _labels = sas4.grant_plan(document, [(self.EQUIP, "equipment", 0, 0, 2)])
        self.assertEqual(len(plan[0][1]), 4, "a piece of equipment is four as well")
        self.assertIn("Test Gun", labels[0])

    def test_grant_read_back_preserves_the_details(self):
        path = self.make()
        _raw, document = sas4.load(path)
        plan, _labels = sas4.grant_plan(document, [(self.WEAPON, "weapon", 12, 10, 2),
                                                   (self.EQUIP, "equipment", 5, 3, 4)])
        ok, _saved, message = sas4.apply_edits(path, plan)
        self.assertTrue(ok, message)

        rows = sas4.claimed_items(sas4.load(path)[1])
        self.assertEqual([(r[1], r[2], r[4], r[5]) for r in rows],
                         [("weapon", self.WEAPON, 12, 10),
                          ("equipment", self.EQUIP, 5, 3)])
        self.assertEqual(rows[1][6], 4, "equipment keeps its slot")
        self.assertIsNone(rows[0][6], "a weapon has no slot")

    def test_indexes_step_by_the_run_not_by_one(self):
        # The trap the format sets: a weapon's trailing 0 looks exactly like the tag that
        # starts another weapon. Interleave the two kinds so a parser that walks positions
        # instead of runs cannot accidentally agree.
        path = self.make()
        _raw, document = sas4.load(path)
        requests = [(self.WEAPON, "weapon", 0, 0, 2), (self.EQUIP, "equipment", 0, 0, 2),
                    (self.WEAPON, "weapon", 1, 1, 2), (self.EQUIP, "equipment", 2, 2, 2)]
        plan, _labels = sas4.grant_plan(document, requests)
        sas4.apply_edits(path, plan)
        rows = sas4.claimed_items(sas4.load(path)[1])
        self.assertEqual([r[0] for r in rows], [0, 4, 8, 12])
        self.assertEqual([r[1] for r in rows],
                         ["weapon", "equipment", "weapon", "equipment"])

    def test_removing_a_run_leaves_no_tail_behind(self):
        """Removing one item must take its whole run, not the tag and dict alone.

        The failure this guards is silent: the file is rewritten with a valid checksum and
        two loose integers where a run used to be, so nothing complains until the game
        reads it.
        """
        path = self.make()
        _raw, document = sas4.load(path)
        plan, _labels = sas4.grant_plan(document, [(self.WEAPON, "weapon", 0, 0, 2),
                                                   (self.EQUIP, "equipment", 0, 0, 2),
                                                   (self.WEAPON, "weapon", 1, 0, 2)])
        sas4.apply_edits(path, plan)

        _raw, document = sas4.load(path)
        rows = sas4.claimed_items(document)
        kept = sas4.drop_claimed(document, [rows[1][0]])[0][1]
        self.assertEqual(len(kept), len(rows) * 4 - 4, "one whole run went")
        for start in range(0, len(kept), 4):
            self.assertIn(kept[start], (0, 1), "element %d should be a tag" % start)
            self.assertIsInstance(kept[start + 1], dict)

    def test_removing_the_middle_item_keeps_the_rest(self):
        path = self.make()
        _raw, document = sas4.load(path)
        plan, _labels = sas4.grant_plan(document, [(self.WEAPON, "weapon", 1, 0, 2),
                                                   (self.EQUIP, "equipment", 2, 0, 2),
                                                   (self.WEAPON, "weapon", 3, 0, 2)])
        sas4.apply_edits(path, plan)

        _raw, document = sas4.load(path)
        rows = sas4.claimed_items(document)
        ok, _saved, message = sas4.apply_edits(path, sas4.drop_claimed(document, [rows[1][0]]))
        self.assertTrue(ok, message)

        left = sas4.claimed_items(sas4.load(path)[1])
        self.assertEqual([(r[1], r[4]) for r in left], [("weapon", 1), ("weapon", 3)],
                         "the equipment in the middle went, both weapons stayed")
        self.assertEqual(model.check(sas4.load(path)[1]), [])

    def test_an_unknown_id_is_refused_before_anything_is_built(self):
        document = model.generate()
        with self.assertRaises(ValueError):
            sas4.grant_plan(document, [(999999, "auto", 0, 0, 2)])

    def test_an_ambiguous_id_has_to_be_told_which(self):
        sas4._ITEM_CACHE = {"weapon": {7: ("Gun Seven", "smg")},
                            "equipment": {7: ("Vest Seven", "vest")}}
        document = model.generate()
        with self.assertRaises(ValueError):
            sas4.grant_plan(document, [(7, "auto", 0, 0, 2)])
        plan, labels = sas4.grant_plan(document, [(7, "weapon", 0, 0, 2)])
        self.assertIn("Gun Seven", labels[0])


class TestMasteries(Temp):
    """The mastery tracks: read them, set them, and keep the two fields agreeing."""

    def test_a_generated_profile_has_every_track(self):
        rows = sas4.mastery_rows(model.generate(), 0)
        self.assertEqual(len(rows), model.MASTERY_SLOTS)
        self.assertTrue(all(xp == 0 and lvl == 0 for _i, xp, lvl, _fits in rows))

    def test_setting_a_level_writes_the_xp_that_supports_it(self):
        document = model.generate()
        plan = sas4.mastery_plan(document, {3: 5, 7: 2})
        self.assertEqual(len(plan), 1, "one value replaced, however many tracks move")
        tracks = plan[0][1]
        self.assertEqual(tracks[3], {"MasteryXp": model.MASTERY_LEVEL_XP[5], "MasteryLvl": 5})
        self.assertEqual(tracks[7], {"MasteryXp": model.MASTERY_LEVEL_XP[2], "MasteryLvl": 2})
        self.assertEqual(tracks[0], {"MasteryXp": 0, "MasteryLvl": 0}, "others untouched")
        self.assertEqual(len(tracks), model.MASTERY_SLOTS)

    def test_out_of_range_is_refused(self):
        document = model.generate()
        for targets in ({model.MASTERY_SLOTS: 1}, {-1: 1}, {0: 6}, {0: -1}):
            with self.assertRaises(ValueError, msg=str(targets)):
                sas4.mastery_plan(document, targets)

    def test_a_slot_with_no_character_is_refused(self):
        """Slots 1-5 of a fresh account are the stub {"Loaded": false} -- no Skills, no
        weapons, no character. Writing progress into one describes a character that was
        never made, and `Loaded` is the field that says which slots are real. It is the
        same field `loaded_profiles` already uses, so a plan and the check that judges it
        agree about what a character is."""
        document = model.generate()
        self.assertEqual(document["Inventory"]["Profile4"], {"Loaded": False})
        with self.assertRaises(ValueError) as caught:
            sas4.mastery_plan(document, {0: 5}, slot=4)
        self.assertIn("4", str(caught.exception))
        with self.assertRaises(ValueError):
            sas4.level_plan(document, 40, slot=4)

    def test_granting_into_an_empty_slot_is_refused_by_name(self):
        """`give --slotprofile 4` already failed, but on the symptom -- "no
        Strongboxes/Claimed in Profile4" -- and then advised listing the item catalogue,
        which has nothing to do with it. All three commands say the same thing now, and
        each names its own flag."""
        document = model.generate()
        cache = sas4._ITEM_CACHE
        sas4._ITEM_CACHE = {"weapon": {129: ("Z-5 Heavy", "smg")}, "equipment": {}}
        try:
            with self.assertRaises(sas4.EmptySlot) as caught:
                sas4.grant_plan(document, [(129, "weapon", 0, 0, None)], slotprofile=4)
            self.assertIn("--slotprofile", str(caught.exception))
            self.assertIsInstance(caught.exception, ValueError, "callers catch ValueError")
        finally:
            sas4._ITEM_CACHE = cache

    def test_an_empty_slot_cannot_be_reached_through_a_global(self):
        """`level --slot 4` used to write nothing to the profile -- three fields skipped --
        and still bump Global/HighestRank, taking a backup for it. A refused slot writes
        nothing at all."""
        document = model.generate(level=5)
        with self.assertRaises(ValueError):
            sas4.level_plan(document, 40, slot=4)
        self.assertEqual(document["Global"]["HighestRank"], 5)

    def test_a_track_that_is_not_a_number_is_reported_not_raised(self):
        """A hand-edited or truncated file can hold a string where a count belongs. The
        checker's job is to say so; crashing tells the person nothing about their file."""
        for field in ("MasteryXp", "MasteryLvl"):
            document = model.generate()
            document["MasteryProgress"]["MasteryProfile0"][0][field] = "3"
            problems = model.check(document)
            self.assertTrue(any(field in line for line in problems),
                            "%s: %r" % (field, problems))

    def test_reading_a_track_that_is_not_a_number_does_not_crash(self):
        """mastery_rows feeds a table. A odd value shows as itself -- normalising it to 0
        would show a clean table for a file that is not clean."""
        document = model.generate()
        document["MasteryProgress"]["MasteryProfile0"][0]["MasteryXp"] = "3"
        document["MasteryProgress"]["MasteryProfile0"][1]["MasteryLvl"] = None
        rows = sas4.mastery_rows(document, 0)
        self.assertEqual(len(rows), model.MASTERY_SLOTS)
        self.assertEqual(rows[0][1], "3", "the raw value is shown, not a stand-in")
        self.assertIsNone(rows[0][3], "no level is claimed for an XP that is not a number")

    def test_setting_and_all_together_is_refused(self):
        """--all used to win over --set silently, so `--set 3=1 --all 5` wrote 5 to every
        track and said nothing about the 1 that was asked for."""
        parser = sas4.build_parser()
        with self.assertRaises(SystemExit):
            parser.parse_args(["mastery", "--set", "3=1", "--all", "5"])

    def test_the_whole_list_is_replaced_because_a_field_cannot_be_pinned(self):
        """Why the plan names the list, not the field.

        A profile holds well over a hundred identical `"MasteryXp":0` fragments, so
        anchor_for cannot make a unique anchor for one track and rightly refuses. The list
        as a whole can be pinned, which is the same move grant_plan makes with Claimed.
        """
        path = self.make()
        _raw, document = sas4.load(path)
        plain = dgdata.decode(read(path))
        with self.assertRaises(ValueError):
            sas4.anchor_for(document, plain, "MasteryProgress/MasteryProfile0[5]/MasteryXp")
        anchor, _length = sas4.anchor_for(document, plain, "MasteryProgress/MasteryProfile0")
        self.assertEqual(plain.count(anchor), 1)

    def test_writing_masteries_end_to_end_stays_consistent(self):
        path = self.make()
        _raw, document = sas4.load(path)
        ok, _saved, message = sas4.apply_edits(path, sas4.mastery_plan(document, {3: 5, 7: 2}))
        self.assertTrue(ok, message)
        rows = sas4.mastery_rows(sas4.load(path)[1], 0)
        self.assertEqual([(i, xp, lvl) for i, xp, lvl, _f in rows if lvl],
                         [(3, model.MASTERY_LEVEL_XP[5], 5), (7, model.MASTERY_LEVEL_XP[2], 2)])
        self.assertEqual(model.check(sas4.load(path)[1]), [])

    def test_a_level_its_xp_cannot_reach_is_caught(self):
        document = model.generate()
        document["MasteryProgress"]["MasteryProfile0"][2] = {"MasteryXp": 0, "MasteryLvl": 5}
        problems = model.check(document)
        self.assertTrue(any("MasteryProfile0[2]" in p for p in problems), problems)

    def test_named_tracks_are_real_indexes(self):
        """Names are only useful if they point at a track that exists."""
        self.assertTrue(model.MASTERY_TRACKS, "at least one track has been established")
        for index, name in model.MASTERY_TRACKS.items():
            self.assertTrue(0 <= index < model.MASTERY_SLOTS, "track %d" % index)
            self.assertTrue(name.strip(), "track %d has a name" % index)
        self.assertEqual(len(set(model.MASTERY_TRACKS.values())),
                         len(model.MASTERY_TRACKS), "no two indexes share a name")
        self.assertIsNone(model.mastery_name(model.MASTERY_SLOTS - 1) if
                          model.MASTERY_SLOTS - 1 not in model.MASTERY_TRACKS else None)

    def test_every_threshold_round_trips_through_the_level_it_names(self):
        for level, needed in enumerate(model.MASTERY_LEVEL_XP):
            self.assertEqual(model.mastery_level_for_xp(needed), level)
            if level:
                self.assertEqual(model.mastery_level_for_xp(needed - 1), level - 1)


class TestRules(Temp):
    """Every tampering the catalogue knows, against the rules meant to catch it."""

    def test_a_generated_profile_is_consistent(self):
        for level in (1, 5, 25, 99):
            self.assertEqual(model.check(model.generate(level=level, money=1234)), [],
                             "level %d" % level)

    def test_structural_attacks_are_all_caught(self):
        for name, attack in model.ATTACKS.items():
            if name.startswith("consistent"):
                continue
            document = model.generate(level=1, money=1000)
            attack(document)
            self.assertNotEqual(model.check(document), [], "%s slipped through" % name)

    def test_consistent_attacks_are_not_caught_and_that_is_the_point(self):
        # If one of these ever starts failing, a rule has been added that claims to detect
        # an edit no single file can reveal -- which would be the rule that is wrong.
        for name, attack in model.ATTACKS.items():
            if not name.startswith("consistent"):
                continue
            document = model.generate(level=1, money=1000)
            attack(document)
            self.assertEqual(model.check(document), [], "%s should be undetectable" % name)


class TestWhereItWrites(Temp):
    """Backups must land somewhere writable, or refuse in a way callers can report."""

    def test_probe_says_no_to_an_impossible_directory(self):
        self.assertTrue(sas4._writable(self.dir))
        blocker = os.path.join(self.dir, "a-file")
        with open(blocker, "w") as handle:
            handle.write("x")
        # A directory cannot be created underneath a regular file, on any platform.
        self.assertFalse(sas4._writable(os.path.join(blocker, "sub")))

    def test_falls_back_when_the_tool_directory_is_read_only(self):
        real = sas4._writable
        try:
            sas4._writable = lambda d: False if d == sas4.HERE else real(d)
            self.assertNotEqual(sas4.data_dir(), sas4.HERE)
            sas4._writable = lambda d: False
            self.assertEqual(sas4.data_dir(), tempfile.gettempdir())
        finally:
            sas4._writable = real

    def test_two_writes_in_one_second_keep_both_backups(self):
        """The backup directory is named to the second; two writes must not share a copy.

        Found by making three edits in a row against a real profile and counting two
        backups: the state between the second and third writes had been overwritten, which
        is precisely the one an undo of the third needs. Granting an item and taking it
        back again is two clicks in the armoury, so this is an ordinary sequence, not a
        contrived one.
        """
        path = self.make(money=1000)
        first = read(path)
        self.assertTrue(sas4.apply_edits(path, [("Inventory/Profile0/Money", 2)])[0])
        between = read(path)
        self.assertTrue(sas4.apply_edits(path, [("Inventory/Profile0/Money", 3)])[0])

        saved = [os.path.join(root, name)
                 for root, _dirs, files in os.walk(sas4.BACKUPS) for name in files]
        self.assertEqual(len(saved), 2, "each write keeps its own backup: %s" % saved)
        kept = [read(p) for p in saved]
        self.assertIn(first, kept, "the state before the first write survives")
        self.assertIn(between, kept, "the state between the two writes survives")

    def test_a_backup_that_cannot_be_written_stops_the_edit(self):
        path = self.make(money=1000)
        original = read(path)
        sas4.BACKUPS = os.path.join(path, "impossible")     # under a file, so never creatable
        ok, saved, message = sas4.apply_edits(path, [("Inventory/Profile0/Money", 7)])
        self.assertFalse(ok)
        self.assertIsNone(saved)
        self.assertIn("backup", message.lower())
        self.assertEqual(read(path), original,
                         "no backup means no write, or the one recorded way to lose a "
                         "character is back")


class TestWindows(Temp):
    """The panels build. Nothing else here touches them, so a refactor breaks them silently.

    All three are `ttk.Frame` so they can be a tab of the combined window or the whole of a
    window of their own. That is the property worth guarding: a panel that quietly went back
    to being a `tk.Tk` still works alone and cannot be a tab at all.

    Skipped where tkinter is absent, which is every machine without a display -- these are
    Windows tools and the rest of the suite runs anywhere.
    """

    PANELS = [("sas4_quick", "Quick"), ("sas4_gear", "Armoury"), ("sas4_gui", "Editor")]

    def setUp(self):
        super().setUp()
        try:
            import tkinter
            self.root = tkinter.Tk()
        except Exception as problem:                 # no tkinter, or no display to open on
            self.skipTest("tkinter is not usable here: %s" % problem)
        self.root.withdraw()

    def tearDown(self):
        try:
            self.root.destroy()
        except Exception:
            pass
        super().tearDown()

    def test_every_panel_builds_into_a_shared_root(self):
        import tkinter as tk
        path = self.make(level=5, money=1000)
        shared = tk.StringVar(value=path)
        for module_name, class_name in self.PANELS:
            panel = getattr(_load(module_name), class_name)(self.root, shared)
            panel.pack(fill="both", expand=True)
            self.assertTrue(panel.winfo_exists(), class_name)
            variable = panel.path_var if class_name == "Editor" else panel.path
            self.assertIs(variable, shared, "%s shares the window's save file" % class_name)

    def test_a_panel_is_a_frame_so_it_can_be_a_tab(self):
        from tkinter import ttk
        for module_name, class_name in self.PANELS:
            self.assertTrue(issubclass(getattr(_load(module_name), class_name), ttk.Frame),
                            "%s has to be a frame to be a tab" % class_name)

    def test_the_hub_builds_tabs_only_as_they_are_selected(self):
        hub_module = _load("sas4_hub")
        hub = hub_module.Hub(self.make())
        try:
            hub.withdraw()
            self.assertEqual(sorted(hub.panels), [0], "only the first tab is built up front")
            for index in range(len(hub_module.PANELS)):
                hub.notebook.select(index)
                hub.update()
            self.assertEqual(sorted(hub.panels), list(range(len(hub_module.PANELS))))
            self.assertTrue(all(p is not None for p in hub.panels.values()))
        finally:
            hub.destroy()


class TestPrivacyGuard(unittest.TestCase):
    """The packaging guard that keeps personal data out of a release."""

    def test_the_scanner_finds_a_planted_token(self):
        source = os.path.join(TOOLS, os.pardir, "make_dist.py")
        if not os.path.exists(source):
            self.skipTest("make_dist.py is not shipped with the tools")
        spec = importlib.util.spec_from_file_location("make_dist", source)
        make_dist = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(make_dist)

        directory = tempfile.mkdtemp(prefix="sas4-guard-")
        try:
            clean = os.path.join(directory, "clean.txt")
            with open(clean, "w") as handle:
                handle.write("nothing personal here\n")
            self.assertEqual(make_dist.scan_for_secrets(clean), [])

            token = make_dist.FORBIDDEN[0]
            dirty = os.path.join(directory, "dirty.txt")
            with open(dirty, "w") as handle:
                handle.write("something %s something\n" % token)
            self.assertEqual(make_dist.scan_for_secrets(dirty), [token])
        finally:
            shutil.rmtree(directory, ignore_errors=True)


if __name__ == "__main__":
    unittest.main(verbosity=2 if "-v" in sys.argv else 1)
